# Array compatible with run_now.sh. Defining it does not start any experiment.
# Priority: self .10/.20; explicit .05 baseline; .50 supplementary observation.
# GPU 0/1/2/3 are examples; adjust them before manually starting a runner.
declare -a COMMANDS=(
    "python main.py -t 1 -lr 0.005 -jr 1.0 -lbs 16 -gr 100 -ls 5 -nc 20 -ncl 100 -data Cifar100 -m Decom_CNN-5-512 -did 0 -algo FedTargetProj -is_regular 1 -regular_lamda 1e-3 -niid 1 -pt pat -cpc 20 --target_client_id 0 --seed 0 --target_proj_mode projection_softmax --projection_self_weight 0.10 -exp_name target0_seed0_projection_softmax_self0p10 -sfn temp/projection_softmax_self0p10 --h5_result_root h5_results/projection_softmax_self0p10 --final-model-root final_models/projection_softmax_self0p10"
    "python main.py -t 1 -lr 0.005 -jr 1.0 -lbs 16 -gr 100 -ls 5 -nc 20 -ncl 100 -data Cifar100 -m Decom_CNN-5-512 -did 1 -algo FedTargetProj -is_regular 1 -regular_lamda 1e-3 -niid 1 -pt pat -cpc 20 --target_client_id 0 --seed 0 --target_proj_mode projection_softmax --projection_self_weight 0.20 -exp_name target0_seed0_projection_softmax_self0p20 -sfn temp/projection_softmax_self0p20 --h5_result_root h5_results/projection_softmax_self0p20 --final-model-root final_models/projection_softmax_self0p20"
    "python main.py -t 1 -lr 0.005 -jr 1.0 -lbs 16 -gr 100 -ls 5 -nc 20 -ncl 100 -data Cifar100 -m Decom_CNN-5-512 -did 2 -algo FedTargetProj -is_regular 1 -regular_lamda 1e-3 -niid 1 -pt pat -cpc 20 --target_client_id 0 --seed 0 --target_proj_mode projection_softmax --projection_self_weight 0.05 -exp_name target0_seed0_projection_softmax_self0p05 -sfn temp/projection_softmax_self0p05 --h5_result_root h5_results/projection_softmax_self0p05 --final-model-root final_models/projection_softmax_self0p05"
    "python main.py -t 1 -lr 0.005 -jr 1.0 -lbs 16 -gr 100 -ls 5 -nc 20 -ncl 100 -data Cifar100 -m Decom_CNN-5-512 -did 3 -algo FedTargetProj -is_regular 1 -regular_lamda 1e-3 -niid 1 -pt pat -cpc 20 --target_client_id 0 --seed 0 --target_proj_mode projection_softmax --projection_self_weight 0.50 -exp_name target0_seed0_projection_softmax_self0p50 -sfn temp/projection_softmax_self0p50 --h5_result_root h5_results/projection_softmax_self0p50 --final-model-root final_models/projection_softmax_self0p50"
)
